kind: pipeline
type: docker
name: gitflow_doc_drone

environment:
  PROJECT_DIR: gitflow_doc

steps:

- name: build
  image: dhub.qingtong123.com/ci/doc_ci
  commands:
   - python scripts/deploy_site.py $PROJECT_DIR


- name: deploy
  image: dhub.qingtong123.com/ci/go_rsync
  environment:
    RSYNC_HOST:
      from_secret: rsync_host
    RSYNC_REMOTEDIR:
      from_secret: rsync_remote_dir
  commands:
   - go_rsync -h $RSYNC_HOST -src $PROJECT_DIR -dst $RSYNC_REMOTEDIR