kind: pipeline
type: docker
name: gitflow_doc_drone

environment:
  PROJECT_DIR: gitflow_doc

steps:

- name: build
  image: dhub.qingtong123.com/ci/doc_ci
  commands:
   - python scripts/deploy_site.py $PROJECT_DIR


- name: deploy
  image: dhub.qingtong123.com/ci/go_rsync
  environment:
    RSYNC_PORT:
      from_secret: www_ssh_port
    RSYNC_REMOTE_ADDR:
      from_secret: www_pub_remote_addr
  commands:
   - go_rsync -port $RSYNC_PORT -src $PROJECT_DIR -remote_addr $RSYNC_REMOTE_ADDR 

---
kind: secret
name: www_pub_remote_addr
get:
  path: secrets/data/docker
  name: www_pub_remote_addr

---
kind: secret
name: www_ssh_port
get:
  path: secrets/data/docker
  name: www_ssh_port