kind: pipeline
type: docker
name: build web

steps:
- name: build
  image: dhub.qingtong123.com/git_ci/gitflow_doc_ci
  environment:
    PORT:
      from_secret: rsync_port
    USR:
      from_secret: rsync_uname
    UPWD:
      from_secret: rsync_pwd
    IP:
      from_secret: rsync_local_ip
    PUBDIR:
      from_secret: rsync_dir
   
  commands:
   - mkdir web
   - python scripts/deploy_site.py web/
   - sshpass -p $UPWD rsync -avue "ssh -p $PORT" web/* $USR@$IP:$PUBDIR